# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 45bf049699f98e88b4ade0ce30f953c697aeae5439f62b4894a056b16c8eaecc146eb8424bb401aba4b959bcbbd85541d50be45471d9a5f17c731f18f216d89e

test:
  secret_key_base: 967d632a177faf744dad6a1faaf1107be3e1cf2c0c4988654d0b29b7740c91c8ce7af62c476ad2d43eaced592483e97b4e3cc1c584c1467ce05e2045cf6d3fd0

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
